options(echo=TRUE)
source("mictest_e.R")
args <- commandArgs(trailingOnly=TRUE)
print(args)
basename <- paste(args[1], args[2], "_", args[3], "_", args[4], "_", args[5], sep="")
dataname <- paste(args[1], args[2], "_groupN-", args[3], "_subjectN-", args[4], "_hlr-", args[5], ".Rdmp", sep="")
source(paste("~/data/bayesmic/", dataname, sep=""))
inits <- initsstan_optim2d()
attach(inits)
dump(names(inits), file=paste("inits/bayesmic/inits-", basename, "_c", args[6], ".Rdmp", sep=""))
